In [50]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [51]:
pip install pandas numpy matplotlib

Requirement already satisfied: pandas in c:\users\admin\miniconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\admin\miniconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\admin\miniconda3\lib\site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\miniconda3\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\miniconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\miniconda3\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\miniconda3\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\miniconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\admin\miniconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\admin\miniconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [52]:
from pathlib import Path
import pandas as pd

# Notebook đang mở trong: C:\Users\ADMIN\Desktop\project2\lol-esports-dashboard\pipeline\notebooks
NOTEBOOK_DIR = Path.cwd()  # hoặc Path().resolve()
PROJECT_ROOT = NOTEBOOK_DIR.parents[1]  # lol-esports-dashboard/

CSV_PATH = PROJECT_ROOT / "pipeline" / "notebooks" / "2025_LoL_esports_match_data_from_OraclesElixir.csv"

print("CSV path:", CSV_PATH)

df = pd.read_csv(CSV_PATH)
df.head()

CSV path: c:\Users\ADMIN\Desktop\project2\lol-esports-dashboard\pipeline\notebooks\2025_LoL_esports_match_data_from_OraclesElixir.csv

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9000\596212648.py:12: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(CSV_PATH)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25,Unnamed: 164
0,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,224.0,-1.0,17.0,1.0,1.0,2.0,2.0,4.0,2.0,NaN
1,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-2363.0,-1444.0,-18.0,0.0,1.0,2.0,1.0,7.0,0.0,NaN
2,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-1552.0,-2465.0,-41.0,1.0,0.0,2.0,1.0,5.0,1.0,NaN
3,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-2613.0,-1156.0,-6.0,1.0,1.0,2.0,6.0,2.0,0.0,NaN
4,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-662.0,-734.0,18.0,0.0,2.0,2.0,0.0,8.0,0.0,NaN

In [53]:
player_df = df[df['position'] != 'team'].copy()
team_df = df[df['position'] == 'team'].copy()

print(player_df.shape)  # số dòng player (≈ 10 dòng / game)
print(team_df.shape)    # số dòng team   (≈ 2 dòng / game)

(99220, 165)
(19844, 165)

In [54]:
player_df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25,Unnamed: 164
0,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,224.0,-1.0,17.0,1.0,1.0,2.0,2.0,4.0,2.0,NaN
1,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-2363.0,-1444.0,-18.0,0.0,1.0,2.0,1.0,7.0,0.0,NaN
2,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-1552.0,-2465.0,-41.0,1.0,0.0,2.0,1.0,5.0,1.0,NaN
3,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-2613.0,-1156.0,-6.0,1.0,1.0,2.0,6.0,2.0,0.0,NaN
4,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-662.0,-734.0,18.0,0.0,2.0,2.0,0.0,8.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119057,LOLTMNT03_323132,complete,NaN,IC,2025,NaN,0,11/22/2025 21:20,4,15.22,...,70.0,781.0,26.0,2.0,3.0,2.0,3.0,4.0,1.0,NaN
119058,LOLTMNT03_323132,complete,NaN,IC,2025,NaN,0,11/22/2025 21:20,4,15.22,...,682.0,444.0,10.0,2.0,7.0,4.0,1.0,9.0,4.0,NaN
119059,LOLTMNT03_323132,complete,NaN,IC,2025,NaN,0,11/22/2025 21:20,4,15.22,...,1965.0,1289.0,64.0,4.0,2.0,1.0,2.0,6.0,1.0,NaN
119060,LOLTMNT03_323132,complete,NaN,IC,2025,NaN,0,11/22/2025 21:20,4,15.22,...,-653.0,688.0,-35.0,2.0,5.0,3.0,2.0,4.0,2.0,NaN
119061,LOLTMNT03_323132,complete,NaN,IC,2025,NaN,0,11/22/2025 21:20,4,15.22,...,-1302.0,111.0,-8.0,0.0,8.0,1.0,3.0,4.0,2.0,NaN

In [55]:
team_df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25,Unnamed: 164
10,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,-6966.0,-5800.0,-30.0,3.0,5.0,10.0,10.0,26.0,3.0,NaN
11,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,...,6966.0,5800.0,30.0,10.0,26.0,3.0,3.0,5.0,10.0,NaN
22,LOLTMNT06_96134,complete,NaN,LFL2,2025,Winter,0,1/11/2025 12:06,1,15.01,...,8377.0,4306.0,99.0,15.0,35.0,8.0,7.0,12.0,15.0,NaN
23,LOLTMNT06_96134,complete,NaN,LFL2,2025,Winter,0,1/11/2025 12:06,1,15.01,...,-8377.0,-4306.0,-99.0,7.0,12.0,15.0,15.0,35.0,8.0,NaN
34,LOLTMNT06_95160,complete,NaN,LFL2,2025,Winter,0,1/11/2025 13:07,1,15.01,...,-5621.0,-4329.0,-107.0,14.0,25.0,14.0,14.0,32.0,14.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119039,LOLTMNT03_323128,complete,NaN,IC,2025,NaN,0,11/22/2025 19:35,2,15.22,...,-1092.0,-3586.0,7.0,14.0,27.0,15.0,15.0,34.0,14.0,NaN
119050,LOLTMNT03_323130,complete,NaN,IC,2025,NaN,0,11/22/2025 20:27,3,15.22,...,-1611.0,-5032.0,3.0,10.0,18.0,12.0,12.0,38.0,10.0,NaN
119051,LOLTMNT03_323130,complete,NaN,IC,2025,NaN,0,11/22/2025 20:27,3,15.22,...,1611.0,5032.0,-3.0,12.0,38.0,10.0,10.0,18.0,12.0,NaN
119062,LOLTMNT03_323132,complete,NaN,IC,2025,NaN,0,11/22/2025 21:20,4,15.22,...,-762.0,-3313.0,-57.0,11.0,27.0,10.0,10.0,25.0,11.0,NaN
119063,LOLTMNT03_323132,complete,NaN,IC,2025,NaN,0,11/22/2025 21:20,4,15.22,...,762.0,3313.0,57.0,10.0,25.0,11.0,11.0,27.0,10.0,NaN

In [56]:
# Cell 4: Drop một số cột không cần thiết (ví dụ, chỉnh lại đúng cột thực tế)
cols_to_drop_player = [
    "game", "url", "datacompleteness", "participantid", "playerid", "teamid",
]
player_df = player_df.drop(columns=[c for c in cols_to_drop_player if c in player_df.columns])

cols_to_drop_team = [
    "url", "datacompleteness", "teamid",
]
team_df = team_df.drop(columns=[c for c in cols_to_drop_team if c in team_df.columns])

player_df.head()
team_df.head()

,gameid,league,year,split,playoffs,date,game,patch,participantid,side,...,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25,Unnamed: 164
10,LOLTMNT03_179647,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,100,Blue,...,-6966.0,-5800.0,-30.0,3.0,5.0,10.0,10.0,26.0,3.0,NaN
11,LOLTMNT03_179647,LFL2,2025,Winter,0,1/11/2025 11:11,1,15.01,200,Red,...,6966.0,5800.0,30.0,10.0,26.0,3.0,3.0,5.0,10.0,NaN
22,LOLTMNT06_96134,LFL2,2025,Winter,0,1/11/2025 12:06,1,15.01,100,Blue,...,8377.0,4306.0,99.0,15.0,35.0,8.0,7.0,12.0,15.0,NaN
23,LOLTMNT06_96134,LFL2,2025,Winter,0,1/11/2025 12:06,1,15.01,200,Red,...,-8377.0,-4306.0,-99.0,7.0,12.0,15.0,15.0,35.0,8.0,NaN
34,LOLTMNT06_95160,LFL2,2025,Winter,0,1/11/2025 13:07,1,15.01,100,Blue,...,-5621.0,-4329.0,-107.0,14.0,25.0,14.0,14.0,32.0,14.0,NaN

In [57]:
import numpy as np

In [58]:
# Cell 5: Player stats aggregate từ player_df

# Kiểm tra cột
required_player_cols = [
    "gameid", "playername", "teamname", "result",
    "kills", "deaths", "assists",
    "dpm", "damageshare", "visionscore",
    "earnedgold", "earned gpm",  # trong file tên là "earned gpm" có khoảng trắng
]
missing_player = [c for c in required_player_cols if c not in player_df.columns]
print("Missing player cols:", missing_player)

# Đổi tên cột có khoảng trắng cho dễ xử lý
player_df = player_df.rename(columns={"earned gpm": "earned_gpm"})

agg_player = (
    player_df
    .groupby(["playername", "teamname"], as_index=False)
    .agg(
        games=("gameid", "nunique"),
        wins=("result", "sum"),
        kills=("kills", "sum"),
        deaths=("deaths", "sum"),
        assists=("assists", "sum"),
        dpm=("dpm", "mean"),
        damageshare=("damageshare", "mean"),
        visionscore=("visionscore", "mean"),
        earnedgold=("earnedgold", "mean"),
        earnedgpm=("earned_gpm", "mean"),
    )
)

agg_player["losses"] = agg_player["games"] - agg_player["wins"]
agg_player["winrate"] = agg_player["wins"] / agg_player["games"]

# KDA: tránh chia cho 0
agg_player["kda"] = (
    (agg_player["kills"] + agg_player["assists"])
    / agg_player["deaths"].replace(0, np.nan)
)
agg_player["kda"] = agg_player["kda"].fillna(
    agg_player["kills"] + agg_player["assists"]
)

players_df_final = agg_player
players_df_final.head()

Missing player cols: []

,playername,teamname,games,wins,kills,deaths,assists,dpm,damageshare,visionscore,earnedgold,earnedgpm,losses,winrate,kda
0,BLWeaksideWizar,Black Lion,2,0,1,8,7,600.204000,0.227602,18.500000,5556.500000,203.342200,2,0.000000,1.000000
1,0ri,Dynamo Eclot Talents,29,11,113,128,181,439.413724,0.173107,28.068966,7015.344828,223.322352,18,0.379310,2.296875
2,1116,Ground Zero Gaming,1,0,5,5,3,632.771900,0.329852,20.000000,8001.000000,280.736800,1,0.000000,1.600000
3,1116,West Point Esports,73,45,458,267,558,865.163889,0.274153,28.068493,9270.273973,310.897082,28,0.616438,3.805243
4,113,Barça eSports,29,11,103,121,211,547.051503,0.206911,37.310345,7588.793103,231.825279,18,0.379310,2.595041

In [59]:
print(team_df.columns)

# 1) Bảng aggregate theo team cho KPI (teams_df_final)
agg_team = (
    team_df
    .groupby("teamname", as_index=False)
    .agg(
        games=("gameid", "nunique"),
        wins=("result", "sum"),
        gamelength=("gamelength", "mean"),
        dragons=("dragons", "mean"),
        opp_dragons=("opp_dragons", "mean"),
        barons=("barons", "mean"),
        opp_barons=("opp_barons", "mean"),
        heralds=("heralds", "mean"),
        opp_heralds=("opp_heralds", "mean"),
        towers=("towers", "mean"),
        opp_towers=("opp_towers", "mean"),
        inhibitors=("inhibitors", "mean"),
        opp_inhibitors=("opp_inhibitors", "mean"),
        turretplates=("turretplates", "mean"),
        opp_turretplates=("opp_turretplates", "mean"),
        firstdragon_rate=("firstdragon", "mean"),
        firstherald_rate=("firstherald", "mean"),
        firstbaron_rate=("firstbaron", "mean"),
        firsttower_rate=("firsttower", "mean"),
    )
)

agg_team["losses"] = agg_team["games"] - agg_team["wins"]
agg_team["winrate"] = agg_team["wins"] / agg_team["games"]

teams_df_final = agg_team

# 2) Bảng match-level cho history (team_matches_df)
#    Suy ra opponent từ gameid + teamname
base_cols = [
    "gameid",
    "year",
    "league",
    "teamname",
    "side",
    "result",
    "dragons",
    "barons",
    "heralds",
    "towers",
    "inhibitors",
]
base_cols = [c for c in base_cols if c in team_df.columns]

tmp = team_df[base_cols].copy()

# self-merge để lấy team còn lại trong cùng game
left = tmp.rename(columns={"teamname": "team", "result": "result_team"})
right = tmp.rename(
    columns={
        "teamname": "opponent",
        "result": "result_opponent",
    }
)

merged = left.merge(
    right[["gameid", "opponent", "result_opponent"]],
    on="gameid",
    how="left",
)

# loại trường hợp self-join (team == opponent)
merged = merged[merged["team"] != merged["opponent"]].copy()

team_matches_df = merged.rename(
    columns={
        "team": "teamname",
        "result_team": "result",
    }
)[
    [
        "gameid",
        "year",
        "league",
        "teamname",
        "side",
        "opponent",
        "result",
        "dragons",
        "barons",
        "heralds",
        "towers",
        "inhibitors",
    ]
]

teams_df_final.head(), team_matches_df.head()

Index(['gameid', 'league', 'year', 'split', 'playoffs', 'date', 'game',
       'patch', 'participantid', 'side',
       ...
       'golddiffat25', 'xpdiffat25', 'csdiffat25', 'killsat25', 'assistsat25',
       'deathsat25', 'opp_killsat25', 'opp_assistsat25', 'opp_deathsat25',
       'Unnamed: 164'],
      dtype='object', length=162)

(         teamname  games  wins   gamelength   dragons  opp_dragons    barons  \
 0     100 Thieves     74    41  2010.621622  2.486486     2.189189  0.689189
 1     3BL Esports      7     1  1772.285714  2.571429     1.714286  0.142857
 2      5M Esports      2     1  1937.000000  2.500000     2.000000  0.500000
 3            7REX     10     6  1979.400000  2.400000     2.300000  0.800000
 4  A One Man Army     48    19  1939.812500  2.083333     2.625000  0.375000

    opp_barons   heralds  opp_heralds  ...  inhibitors  opp_inhibitors  \
 0    0.418919  0.513514     0.486486  ...    0.945946        0.689189
 1    0.571429  0.428571     0.428571  ...    0.142857        1.000000
 2    0.500000  0.500000     0.500000  ...    0.500000        2.000000
 3    0.400000  0.600000     0.400000  ...    1.000000        0.600000
 4    0.708333  0.500000     0.500000  ...    0.645833        1.041667

    turretplates  opp_turretplates  firstdragon_rate  firstherald_rate  \
 0      3.364865          3.621622          0.554054          0.513514
 1      4.000000          5.857143          0.857143          0.428571
 2      3.000000          6.500000          1.000000          0.500000
 3      3.200000          2.800000          0.500000          0.600000
 4      3.666667          3.645833          0.395833          0.500000

    firstbaron_rate  firsttower_rate  losses   winrate
 0         0.554054         0.459459      33  0.554054
 1         0.142857         0.285714       6  0.142857
 2         0.000000         0.000000       1  0.500000
 3         0.500000         0.800000       4  0.600000
 4         0.291667         0.458333      29  0.395833

 [5 rows x 22 columns],
              gameid  year league                 teamname  side  \
 1  LOLTMNT03_179647  2025   LFL2                 IziDream  Blue
 2  LOLTMNT03_179647  2025   LFL2             Team Valiant   Red
 5   LOLTMNT06_96134  2025   LFL2            Esprit Shōnen  Blue
 6   LOLTMNT06_96134  2025   LFL2                Skillcamp   Red
 9   LOLTMNT06_95160  2025   LFL2  Karmine Corp Blue Stars  Blue

              opponent  result  dragons  barons  heralds  towers  inhibitors
 1        Team Valiant       0      0.0     0.0      0.0     3.0         0.0
 2            IziDream       1      2.0     1.0      1.0     9.0         2.0
 5           Skillcamp       1      3.0     1.0      1.0    11.0         3.0
 6       Esprit Shōnen       0      2.0     0.0      0.0     2.0         0.0
 9  Project Conquerors       0      0.0     0.0      0.0     3.0         0.0  )

In [60]:
# Cell 7: Champion stats aggregate từ player_df

required_champ_cols = [
    "champion", "gameid", "result",
    "kills", "deaths", "assists",
    "dpm", "damageshare", "visionscore",
    "earnedgold", "earned_gpm",
    "firstblood",      # mới
    "golddiffat15",    # mới
]
missing_champ = [c for c in required_champ_cols if c not in player_df.columns]
print("Missing champion cols:", missing_champ)

champ_agg = (
    player_df
    .groupby("champion", as_index=False)
    .agg(
        games=("gameid", "nunique"),
        wins=("result", "sum"),
        kills=("kills", "mean"),
        deaths=("deaths", "mean"),
        assists=("assists", "mean"),
        dpm=("dpm", "mean"),
        damageshare=("damageshare", "mean"),
        visionscore=("visionscore", "mean"),
        goldpermin=("earned_gpm", "mean"),
        firstblood=("firstblood", "sum"),          # tổng số lần first blood
        golddiffat15=("golddiffat15", "mean"),     # gold diff @15 trung bình
    )
)

champ_agg["winrate"] = champ_agg["wins"] / champ_agg["games"]
champ_agg["firstblood_rate"] = champ_agg["firstblood"] / champ_agg["games"]

champions_df_final = champ_agg
champions_df_final.head()

Missing champion cols: []

,champion,games,wins,kills,deaths,assists,dpm,damageshare,visionscore,goldpermin,firstblood,golddiffat15,winrate,firstblood_rate
0,Aatrox,959,501,3.399374,3.094891,5.115746,632.515219,0.227229,28.647550,257.919887,101.0,24.163333,0.522419,0.105318
1,Ahri,1617,777,4.090909,2.497217,7.416821,686.267783,0.253714,33.555349,276.775025,310.0,62.766156,0.480519,0.191713
2,Akali,713,342,5.486676,3.237027,4.786816,643.590281,0.234846,28.960729,274.518566,123.0,100.670886,0.479663,0.172511
3,Akshan,12,6,5.583333,3.916667,4.500000,676.691033,0.237773,20.416667,274.320108,2.0,-425.416667,0.500000,0.166667
4,Alistar,2370,1221,0.641772,4.034177,11.129536,164.196275,0.061062,106.976793,113.047397,581.0,-92.391753,0.515190,0.245148

In [61]:
# team_df: chỉ chứa dòng team (position == "team")

total_matches = team_df["gameid"].nunique()
total_players = player_df["playername"].nunique()
total_teams = team_df["teamname"].nunique()
total_champions = player_df["champion"].nunique()

# Chuẩn hoá side về lowercase cho chắc
team_df["side_norm"] = team_df["side"].str.lower()

# Blue side
blue_teams = team_df[team_df["side_norm"] == "blue"]
blue_games = blue_teams["gameid"].nunique()
blue_wins = int((blue_teams["result"] == 1).sum())
blue_side_winrate = blue_wins / blue_games if blue_games > 0 else 0.0

# Red side
red_teams = team_df[team_df["side_norm"] == "red"]
red_games = red_teams["gameid"].nunique()
red_wins = int((red_teams["result"] == 1).sum())
red_side_winrate = red_wins / red_games if red_games > 0 else 0.0

print("blue_games:", blue_games, "blue_wins:", blue_wins)
print("red_games:", red_games, "red_wins:", red_wins)

overview_dict = {
    "total_matches": int(total_matches),
    "total_players": int(total_players),
    "total_teams": int(total_teams),
    "total_champions": int(total_champions),
    "blue_side_winrate": float(blue_side_winrate),
    "red_side_winrate": float(red_side_winrate),
}
overview_dict

blue_games: 9922 blue_wins: 5297
red_games: 9922 red_wins: 4625

{'total_matches': 9922,
 'total_players': 2923,
 'total_teams': 443,
 'total_champions': 171,
 'blue_side_winrate': 0.5338641402942955,
 'red_side_winrate': 0.4661358597057045}

In [62]:
# Cell 9: Association rules cho player (demo đơn giản)
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Sample cho nhanh
sample = player_df.sample(min(len(player_df), 5000), random_state=42)

transactions = []
for _, row in sample.iterrows():
    items = []
    items.append(f"champ_{row['champion']}")
    items.append(f"role_{row['position']}")
    if row["result"] == 1:
        items.append("result_win")
    else:
        items.append("result_loss")
    transactions.append(items)

te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
trans_df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = apriori(trans_df, min_support=0.02, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.4)

rules_win = rules[rules["consequents"].astype(str).str.contains("result_win")].copy()
rules_win = rules_win.sort_values("lift", ascending=False)

def fs_to_str(fs):
    return ", ".join(sorted(list(fs)))

player_rules_df = rules_win.copy()
player_rules_df["antecedent"] = player_rules_df["antecedents"].apply(fs_to_str)
player_rules_df["consequent"] = player_rules_df["consequents"].apply(fs_to_str)

player_rules_df = player_rules_df[
    ["antecedent", "consequent", "support", "confidence", "lift"]
].reset_index(drop=True)

player_rules_df.head()

  antecedent  consequent  support  confidence      lift
0   role_top  result_win   0.1042    0.517378  1.031867
1   role_jng  result_win   0.1012    0.507014  1.011197
2   role_mid  result_win   0.0988    0.497984  0.993187
3   role_sup  result_win   0.0984    0.492986  0.983219
4   role_bot  result_win   0.0988    0.491542  0.980340

In [63]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\admin\miniconda3\lib\site-packages (22.0.0)
Note: you may need to restart the kernel to use updated packages.

In [64]:
# Cell 10: Export cho backend
from pathlib import Path
import json
import pandas as pd

pd.set_option("io.parquet.engine", "pyarrow")

# Ép các cột dễ lỗi (date/split) về string
for df_ in [players_df_final, teams_df_final, champions_df_final, team_matches_df]:
    for col in df_.columns:
        col_lower = col.lower()
        if "date" in col_lower or "split" in col_lower:
            df_[col] = df_[col].astype(str)

# Làm tròn tất cả cột số xuống 2 chữ số thập phân
players_df_final = players_df_final.round(2)
teams_df_final = teams_df_final.round(2)
team_matches_df = team_matches_df.round(2)
champions_df_final = champions_df_final.round(2)
player_rules_df = player_rules_df.round(2)

PROJECT_ROOT = Path.cwd().parents[1]  # nếu notebook ở pipeline/notebooks
BACKEND_PROCESSED_DIR = PROJECT_ROOT / "backend" / "data" / "processed"
BACKEND_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

players_path = BACKEND_PROCESSED_DIR / "players.parquet"
teams_path = BACKEND_PROCESSED_DIR / "teams.parquet"              # agg
team_matches_path = BACKEND_PROCESSED_DIR / "team_matches.parquet"  # match-level
champs_path = BACKEND_PROCESSED_DIR / "champions.parquet"
player_rules_path = BACKEND_PROCESSED_DIR / "player_rules.parquet"
champion_rules_path = BACKEND_PROCESSED_DIR / "champion_rules.parquet"
overview_path = BACKEND_PROCESSED_DIR / "overview.json"

# Ghi parquet
players_df_final.to_parquet(players_path, index=False, engine="pyarrow")
teams_df_final.to_parquet(teams_path, index=False, engine="pyarrow")
team_matches_df.to_parquet(team_matches_path, index=False, engine="pyarrow")
champions_df_final.to_parquet(champs_path, index=False, engine="pyarrow")
player_rules_df.to_parquet(player_rules_path, index=False, engine="pyarrow")

# Champion rules placeholder
pd.DataFrame(
    columns=["rule_type", "champ1", "champ2", "games", "wins", "winrate", "lift"]
).to_parquet(champion_rules_path, index=False, engine="pyarrow")

# Ghi overview.json (đã tạo ở Cell 8)
with open(overview_path, "w", encoding="utf-8") as f:
    json.dump(overview_dict, f, ensure_ascii=False, indent=2)

players_path, teams_path, team_matches_path, champs_path, player_rules_path, champion_rules_path, overview_path

(WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/players.parquet'),
 WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/teams.parquet'),
 WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/team_matches.parquet'),
 WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/champions.parquet'),
 WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/player_rules.parquet'),
 WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/champion_rules.parquet'),
 WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/overview.json'))

In [65]:
import pandas as pd
from pathlib import Path

# 1. Đọc file champion_rules ở thư mục backend/data/processed
PROJECT_ROOT = Path.cwd().parents[1]  # notebook ở pipeline/notebooks -> lên project root
rules_path = PROJECT_ROOT / "backend" / "data" / "processed" / "champion_rules.parquet"

print("File:", rules_path)
print("Exists:", rules_path.exists())

champion_rules_df = pd.read_parquet(rules_path)
print("Shape:", champion_rules_df.shape)
print("Columns:", champion_rules_df.columns.tolist())

# 2. Lọc rule_type = synergy và một số điều kiện tối thiểu
df_pairs = champion_rules_df[champion_rules_df["rule_type"] == "synergy"].copy()
print("Synergy rows:", df_pairs.shape[0])

# Bỏ cặp quá ít trận, ví dụ < 10 game
df_pairs = df_pairs[df_pairs["games"] >= 5]
print("Synergy rows after games>=10:", df_pairs.shape[0])

# 3. Sort theo winrate (và games) rồi xem top 10
df_pairs = df_pairs.sort_values(
    by=["winrate", "games"],
    ascending=[False, False],
)

top10 = df_pairs.head(10).copy()
display(top10[["champ1", "champ2", "games", "wins", "winrate", "lift"]])

File: c:\Users\ADMIN\Desktop\project2\lol-esports-dashboard\backend\data\processed\champion_rules.parquet
Exists: True
Shape: (0, 7)
Columns: ['rule_type', 'champ1', 'champ2', 'games', 'wins', 'winrate', 'lift']
Synergy rows: 0
Synergy rows after games>=10: 0

Empty DataFrame
Columns: [champ1, champ2, games, wins, winrate, lift]
Index: []

In [66]:
team_matches_df

,gameid,year,league,teamname,side,opponent,result,dragons,barons,heralds,towers,inhibitors
1,LOLTMNT03_179647,2025,LFL2,IziDream,Blue,Team Valiant,0,0.0,0.0,0.0,3.0,0.0
2,LOLTMNT03_179647,2025,LFL2,Team Valiant,Red,IziDream,1,2.0,1.0,1.0,9.0,2.0
5,LOLTMNT06_96134,2025,LFL2,Esprit Shōnen,Blue,Skillcamp,1,3.0,1.0,1.0,11.0,3.0
6,LOLTMNT06_96134,2025,LFL2,Skillcamp,Red,Esprit Shōnen,0,2.0,0.0,0.0,2.0,0.0
9,LOLTMNT06_95160,2025,LFL2,Karmine Corp Blue Stars,Blue,Project Conquerors,0,0.0,0.0,0.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
39678,LOLTMNT03_323128,2025,IC,UCAM Esports,Red,LUA Gaming,0,3.0,0.0,1.0,3.0,0.0
39681,LOLTMNT03_323130,2025,IC,LUA Gaming,Blue,UCAM Esports,0,0.0,0.0,1.0,3.0,0.0
39682,LOLTMNT03_323130,2025,IC,UCAM Esports,Red,LUA Gaming,1,3.0,1.0,0.0,8.0,1.0
39685,LOLTMNT03_323132,2025,IC,UCAM Esports,Blue,LUA Gaming,0,1.0,0.0,0.0,2.0,0.0
39686,LOLTMNT03_323132,2025,IC,LUA Gaming,Red,UCAM Esports,1,4.0,1.0,1.0,9.0,2.0

In [67]:
import pandas as pd
from itertools import combinations

# 1) Kiểm tra cột
cols_needed = ["gameid", "teamname", "position", "champion", "result"]
for c in cols_needed:
    assert c in player_df.columns, f"Thiếu cột {c} trong player_df"

df = player_df[cols_needed].copy()
df["gameid"] = df["gameid"].astype(str)
df["teamname"] = df["teamname"].astype(str)
df["position"] = df["position"].astype(str).str.upper()
df["champion"] = df["champion"].astype(str)
df["result"] = df["result"].astype(int)

# Hàm tiện ích: tạo cặp (posA, posB) trong cùng team
def build_pair_df(df_pos_a, df_pos_b, label):
    merged = df_pos_a.merge(
        df_pos_b,
        on=["gameid", "teamname"],
        suffixes=("_a", "_b"),
    )
    pairs = merged[["gameid", "teamname", "champion_a", "champion_b", "result_a"]].copy()
    pairs.rename(
        columns={
            "champion_a": f"{label}_1",
            "champion_b": f"{label}_2",
            "result_a": "win",
        },
        inplace=True,
    )
    return pairs

# 2) Tách DataFrame theo vị trí
mid_df  = df[df["position"] == "MID"]
jng_df  = df[df["position"].isin(["JNG", "JUNGLE"])]
bot_df  = df[df["position"].isin(["ADC", "BOT", "BOTTOM"])]
sup_df  = df[df["position"].isin(["SUP", "SUPPORT"])]

# 3) Tạo cặp mid–jng và bot–sup trong cùng team
mid_jng_pairs = build_pair_df(mid_df, jng_df, "champ")
bot_sup_pairs = build_pair_df(bot_df, sup_df, "champ")

# 4) Tổng hợp, tính winrate cho từng loại cặp
def aggregate_pairs(pairs_df, col1, col2):
    agg = (
        pairs_df
        .groupby([col1, col2], as_index=False)
        .agg(
            games=("win", "size"),
            wins=("win", "sum"),
        )
    )
    agg["winrate"] = agg["wins"] / agg["games"]
    return agg

mid_jng_stats = aggregate_pairs(mid_jng_pairs, "champ_1", "champ_2")
bot_sup_stats = aggregate_pairs(bot_sup_pairs, "champ_1", "champ_2")

# 5) Lọc cặp đủ số game và sort theo winrate + games
min_games = 10

mid_jng_stats = (
    mid_jng_stats[mid_jng_stats["games"] >= min_games]
    .sort_values(by=["winrate", "games"], ascending=[False, False])
    .reset_index(drop=True)
)
bot_sup_stats = (
    bot_sup_stats[bot_sup_stats["games"] >= min_games]
    .sort_values(by=["winrate", "games"], ascending=[False, False])
    .reset_index(drop=True)
)

# 6) Làm tròn 2 chữ số cho winrate
mid_jng_stats["winrate"] = mid_jng_stats["winrate"].round(2)
bot_sup_stats["winrate"] = bot_sup_stats["winrate"].round(2)

# 7) Đổi tên cột để hiện rõ MID/JNG và BOT/SUP
mid_jng_stats = mid_jng_stats.rename(
    columns={
        "champ_1": "mid_champ",
        "champ_2": "jng_champ",
    }
)

bot_sup_stats = bot_sup_stats.rename(
    columns={
        "champ_1": "bot_champ",
        "champ_2": "sup_champ",
    }
)

mid_jng_stats.head(20), bot_sup_stats.head(20)

(       mid_champ  jng_champ  games  wins  winrate
 0          Galio    Skarner     16    14     0.88
 1        Taliyah    Kindred     13    11     0.85
 2          Annie      Poppy     14    11     0.79
 3          Jayce    Skarner     13    10     0.77
 4     Cassiopeia   Pantheon     12     9     0.75
 5           Azir       Zyra     15    11     0.73
 6          Akali     Lillia     11     8     0.73
 7         Aurora     Lillia     11     8     0.73
 8        LeBlanc         Vi     11     8     0.73
 9         Syndra    Lee Sin     11     8     0.73
 10        Viktor     Lillia     21    15     0.71
 11      Tristana    Nidalee     17    12     0.71
 12          Azir  Dr. Mundo     10     7     0.70
 13          Ryze        Jax     10     7     0.70
 14  Twisted Fate   Xin Zhao     10     7     0.70
 15          Yone      Poppy     10     7     0.70
 16          Yone      Ivern     25    17     0.68
 17          Hwei   Nocturne     24    16     0.67
 18       Orianna    Lee Sin     21    14     0.67
 19          Yone   Pantheon     15    10     0.67,
    bot_champ   sup_champ  games  wins  winrate
 0       Jinx  Blitzcrank     15    12     0.80
 1       Jinx       Poppy     12     9     0.75
 2    Smolder       Poppy     14    10     0.71
 3     Yunara       Karma     14    10     0.71
 4      Varus        Bard     59    41     0.69
 5    Caitlyn     Alistar     13     9     0.69
 6    Kalista       Leona     27    18     0.67
 7      Senna        Bard     12     8     0.67
 8    Caitlyn       Braum     50    33     0.66
 9      Sivir       Poppy     29    19     0.66
 10   Caitlyn       Neeko     40    26     0.65
 11      Ashe       Poppy     20    13     0.65
 12    Yunara        Bard     37    24     0.65
 13    Yunara       Poppy     17    11     0.65
 14  Aphelios       Braum     33    21     0.64
 15     Xayah       Poppy     24    15     0.62
 16     Xayah  Blitzcrank     16    10     0.62
 17    Kai'Sa       Poppy     71    44     0.62
 18     Varus       Poppy     89    55     0.62
 19    Kai'Sa        Pyke     23    14     0.61)

In [68]:
import pandas as pd
from itertools import combinations
from mlxtend.frequent_patterns import apriori, association_rules

# ===== 1) Chuẩn hoá player_df =====
cols_needed = ["gameid", "teamname", "position", "champion", "result"]
for c in cols_needed:
    assert c in player_df.columns, f"Thiếu cột {c} trong player_df"

df = player_df[cols_needed].copy()
df["gameid"] = df["gameid"].astype(str)
df["teamname"] = df["teamname"].astype(str)
df["position"] = df["position"].astype(str).str.upper()
df["champion"] = df["champion"].astype(str)
df["result"] = df["result"].astype(int)

# ===== 2) Tách theo vị trí =====
mid_df = df[df["position"] == "MID"]
jng_df = df[df["position"].isin(["JNG", "JUNGLE"])]
bot_df = df[df["position"].isin(["ADC", "BOT", "BOTTOM"])]
sup_df = df[df["position"].isin(["SUP", "SUPPORT"])]

# ===== 3) Hàm tạo cặp trong cùng team =====
def build_pair_df(df_pos_a, df_pos_b, label):
    merged = df_pos_a.merge(
        df_pos_b,
        on=["gameid", "teamname"],
        suffixes=("_a", "_b"),
    )
    pairs = merged[["gameid", "teamname", "champion_a", "champion_b", "result_a"]].copy()
    pairs.rename(
        columns={
            "champion_a": f"{label}_1",
            "champion_b": f"{label}_2",
            "result_a": "win",
        },
        inplace=True,
    )
    return pairs

mid_jng_pairs = build_pair_df(mid_df, jng_df, "champ")
bot_sup_pairs = build_pair_df(bot_df, sup_df, "champ")

# ===== 4) Tổng hợp winrate cặp MID–JNG, BOT–SUP =====
def aggregate_pairs(pairs_df, col1, col2):
    agg = (
        pairs_df
        .groupby([col1, col2], as_index=False)
        .agg(
            games=("win", "size"),
            wins=("win", "sum"),
        )
    )
    agg["winrate"] = agg["wins"] / agg["games"]
    return agg

mid_jng_stats = aggregate_pairs(mid_jng_pairs, "champ_1", "champ_2")
bot_sup_stats = aggregate_pairs(bot_sup_pairs, "champ_1", "champ_2")

min_games = 10

mid_jng_stats = (
    mid_jng_stats[mid_jng_stats["games"] >= min_games]
    .sort_values(by=["winrate", "games"], ascending=[False, False])
    .reset_index(drop=True)
)
bot_sup_stats = (
    bot_sup_stats[bot_sup_stats["games"] >= min_games]
    .sort_values(by=["winrate", "games"], ascending=[False, False])
    .reset_index(drop=True)
)

mid_jng_stats["winrate"] = mid_jng_stats["winrate"].round(2)
bot_sup_stats["winrate"] = bot_sup_stats["winrate"].round(2)

mid_jng_stats = mid_jng_stats.rename(
    columns={"champ_1": "mid_champ", "champ_2": "jng_champ"}
)
bot_sup_stats = bot_sup_stats.rename(
    columns={"champ_1": "bot_champ", "champ_2": "sup_champ"}
)

# ===== 5) Luật kết hợp MID–JNG =====
mid_jng = mid_df.merge(
    jng_df,
    on=["gameid", "teamname"],
    suffixes=("_mid", "_jng"),
)

wins_mj = mid_jng[mid_jng["result_mid"] == 1].copy()
wins_mj["item_mid"] = "MID_" + wins_mj["champion_mid"].astype(str)
wins_mj["item_jng"] = "JNG_" + wins_mj["champion_jng"].astype(str)

transactions_mj = wins_mj[["item_mid", "item_jng"]]
all_items_mj = sorted(
    set(transactions_mj["item_mid"]).union(set(transactions_mj["item_jng"]))
)

def encode_row_mj(row):
    return [1 if item in row.values else 0 for item in all_items_mj]

encoded_mj = transactions_mj.apply(encode_row_mj, axis=1, result_type="expand")
encoded_mj.columns = all_items_mj

freq_itemsets_mj = apriori(encoded_mj, min_support=0.01, use_colnames=True)
rules_all_mj = association_rules(freq_itemsets_mj, metric="confidence", min_threshold=0.05)

def has_mid(items): return any(i.startswith("MID_") for i in items)
def has_jng(items): return any(i.startswith("JNG_") for i in items)

rules_mid_to_jng = rules_all_mj[
    rules_all_mj["antecedents"].apply(has_mid) &
    rules_all_mj["consequents"].apply(has_jng)
].copy()

def unpack_rule_mj(row):
    a = next(iter(row["antecedents"]))
    c = next(iter(row["consequents"]))
    return pd.Series(
        {
            "pair_type": "MID_JNG",
            "role1": "MID", "champ1": a.replace("MID_", ""),
            "role2": "JNG", "champ2": c.replace("JNG_", ""),
            "support": row["support"],
            "confidence": row["confidence"],
            "lift": row["lift"],
        }
    )

rules_mid_df = rules_mid_to_jng.apply(unpack_rule_mj, axis=1)

# ===== 6) Luật kết hợp BOT–SUP =====
bot_sup = bot_df.merge(
    sup_df,
    on=["gameid", "teamname"],
    suffixes=("_bot", "_sup"),
)

wins_bs = bot_sup[bot_sup["result_bot"] == 1].copy()
wins_bs["item_bot"] = "BOT_" + wins_bs["champion_bot"].astype(str)
wins_bs["item_sup"] = "SUP_" + wins_bs["champion_sup"].astype(str)

transactions_bs = wins_bs[["item_bot", "item_sup"]]
all_items_bs = sorted(
    set(transactions_bs["item_bot"]).union(set(transactions_bs["item_sup"]))
)

def encode_row_bs(row):
    return [1 if item in row.values else 0 for item in all_items_bs]

encoded_bs = transactions_bs.apply(encode_row_bs, axis=1, result_type="expand")
encoded_bs.columns = all_items_bs

freq_itemsets_bs = apriori(encoded_bs, min_support=0.01, use_colnames=True)
rules_all_bs = association_rules(freq_itemsets_bs, metric="confidence", min_threshold=0.05)

def has_bot(items): return any(i.startswith("BOT_") for i in items)
def has_sup(items): return any(i.startswith("SUP_") for i in items)

rules_bot_to_sup = rules_all_bs[
    rules_all_bs["antecedents"].apply(has_bot) &
    rules_all_bs["consequents"].apply(has_sup)
].copy()

def unpack_rule_bs(row):
    a = next(iter(row["antecedents"]))
    c = next(iter(row["consequents"]))
    return pd.Series(
        {
            "pair_type": "BOT_SUP",
            "role1": "BOT", "champ1": a.replace("BOT_", ""),
            "role2": "SUP", "champ2": c.replace("SUP_", ""),
            "support": row["support"],
            "confidence": row["confidence"],
            "lift": row["lift"],
        }
    )

rules_bot_df = rules_bot_to_sup.apply(unpack_rule_bs, axis=1)

# ===== 7) Gộp & làm tròn luật kết hợp =====
pair_rules_df = pd.concat([rules_mid_df, rules_bot_df], ignore_index=True)
pair_rules_df[["support", "confidence", "lift"]] = pair_rules_df[["support", "confidence", "lift"]].round(3)
pair_rules_df = pd.concat([rules_mid_df, rules_bot_df], ignore_index=True)
pair_rules_df[["support", "confidence", "lift"]] = pair_rules_df[["support", "confidence", "lift"]].round(3)

# Sắp theo support giảm dần, sau đó confidence, rồi lift
pair_rules_df = pair_rules_df.sort_values(
    by=["support", "confidence", "lift"],
    ascending=[False, False, False]
).reset_index(drop=True)


mid_jng_stats.head(), bot_sup_stats.head(), pair_rules_df.head()

(    mid_champ jng_champ  games  wins  winrate
 0       Galio   Skarner     16    14     0.88
 1     Taliyah   Kindred     13    11     0.85
 2       Annie     Poppy     14    11     0.79
 3       Jayce   Skarner     13    10     0.77
 4  Cassiopeia  Pantheon     12     9     0.75,
   bot_champ   sup_champ  games  wins  winrate
 0      Jinx  Blitzcrank     15    12     0.80
 1      Jinx       Poppy     12     9     0.75
 2   Smolder       Poppy     14    10     0.71
 3    Yunara       Karma     14    10     0.71
 4     Varus        Bard     59    41     0.69,
   pair_type role1   champ1 role2    champ2  support  confidence   lift
 0   BOT_SUP   BOT    Xayah   SUP     Rakan    0.033       0.565  4.898
 1   BOT_SUP   BOT    Varus   SUP      Rell    0.026       0.198  1.315
 2   MID_JNG   MID  Taliyah   JNG  Xin Zhao    0.022       0.194  1.491
 3   MID_JNG   MID     Yone   JNG   Sejuani    0.021       0.335  4.578
 4   BOT_SUP   BOT   Ezreal   SUP     Leona    0.021       0.191  2.003)

In [69]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]
BACKEND_PROCESSED_DIR = PROJECT_ROOT / "backend" / "data" / "processed"
BACKEND_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

mid_jng_path = BACKEND_PROCESSED_DIR / "mid_jng_pairs.parquet"
bot_sup_path = BACKEND_PROCESSED_DIR / "bot_sup_pairs.parquet"
pair_rules_path = BACKEND_PROCESSED_DIR / "pair_rules.parquet"

# Đảm bảo đã sort pair_rules_df theo support trước đó
# pair_rules_df = pair_rules_df.sort_values(...)

mid_jng_stats.to_parquet(mid_jng_path, index=False, engine="pyarrow")
bot_sup_stats.to_parquet(bot_sup_path, index=False, engine="pyarrow")
pair_rules_df.to_parquet(pair_rules_path, index=False, engine="pyarrow")

mid_jng_path, bot_sup_path, pair_rules_path

(WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/mid_jng_pairs.parquet'),
 WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/bot_sup_pairs.parquet'),
 WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/pair_rules.parquet'))

In [70]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]
BACKEND_PROCESSED_DIR = PROJECT_ROOT / "backend" / "data" / "processed"
BACKEND_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

team_champ_perf_path = BACKEND_PROCESSED_DIR / "team_champion_performance.parquet"

# Giả sử team_df đã có: teamname, result (1/0), pick1..pick5
picks = team_df.melt(
    id_vars=["teamname", "result"],
    value_vars=["pick1", "pick2", "pick3", "pick4", "pick5"],
    var_name="slot",
    value_name="picked_champion",
)

champ_stats = (
    picks.groupby(["teamname", "picked_champion"])
    .agg(
        games=("picked_champion", "count"),
        wins=("result", "sum"),
    )
    .reset_index()
)

champ_stats = champ_stats.rename(columns={"picked_champion": "champion"})
champ_stats["winrate"] = champ_stats["wins"] / champ_stats["games"]

champ_stats.to_parquet(team_champ_perf_path, index=False, engine="pyarrow")

team_champ_perf_path

WindowsPath('c:/Users/ADMIN/Desktop/project2/lol-esports-dashboard/backend/data/processed/team_champion_performance.parquet')

In [77]:
from pathlib import Path
import pandas as pd

# 1) Gom pick1–pick5 thành 1 cột (tránh trùng tên)
picks = team_df.melt(
    id_vars=["gameid", "result"],
    value_vars=["pick1", "pick2", "pick3", "pick4", "pick5"],
    var_name="slot",
    value_name="picked_champion",   # ĐỔI TÊN NÀY
)

# 2) Tính số trận & số trận thắng theo champion
champ_agg = (
    picks.groupby("picked_champion", as_index=False)
    .agg(
        games=("gameid", "nunique"),
        wins=("result", "sum"),
    )
)

champ_agg = champ_agg.rename(columns={"picked_champion": "champion"})
champ_agg["winrate"] = champ_agg["wins"] / champ_agg["games"]

# 3) Lưu parquet vào backend/data/processed
PROJECT_ROOT = Path.cwd().parents[1]
BACKEND_PROCESSED_DIR = PROJECT_ROOT / "backend" / "data" / "processed"
BACKEND_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

champ_overview_path = BACKEND_PROCESSED_DIR / "overview_champion_stats.parquet"
champ_agg.to_parquet(champ_overview_path, index=False, engine="pyarrow")